kind: pipeline
type: docker
name: test

trigger:
  event:
   - pull_request

steps:
  - name: lint chart
    image: alpine/helm
    commands:
      - helm lint

  - name: local render template chart
    image: alpine/helm
    commands:
      - helm template ollama-test . --debug

  - name: test chart
    image: quay.io/helmpack/chart-testing
    commands:
      - ls /root/.kube
      - cat /root/.kube/config
      - kubectl cluster-info
      - ct install --chart-dirs . --charts .
    depends_on:
      - kind
    volumes:
      - name: dockersock
        path: /var/run
      - name: kubeconfig
        path: /root/.kube



services:
  - name: docker-service
    image: docker:dind
    privileged: true
    volumes:
    - name: dockersock
      path: /var/run

  - name: kind
    image: otwld/drone-kind
    privileged: true
    settings:
      verbose: 1
      cluster_name: "helm-testing"
    volumes:
      - name: dockersock
        path: /var/run
      - name: kubeconfig
        path: /root/.kube
    depends_on:
      - docker-service

volumes:
  - name: dockersock
    temp: {}
  - name: kubeconfig
    temp: {}

---
kind: pipeline
type: docker
name: publish


trigger:
  event:
  - promote
  branch:
   - main

steps:
  - name: publish helm chart to github pages
    image: otwld/drone-chart-releaser-github-pages
    settings:
      cr_token:
        from_secret: github_access_token
      skip_existing: true
      root_package: true