kind: pipeline
type: docker
name: helm-lint

services: 
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

steps:
- name: setup-kind
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  commands:
    - sleep 5 # give docker enough time to start
    - apk add --no-cache curl bash
    - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
    - chmod +x ./kind
    - mv ./kind /usr/local/bin/kind
    - kind create cluster
    - export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"

- name: setup-kubectl
  image: bitnami/kubectl:1.21
  user: root
  commands:
    - kubectl version --client
    - kubectl cluster-info

- name: setup-helm
  image: alpine/helm:3.5.4
  commands:
    - helm version

- name: wait-for-kind
  image: bitnami/kubectl:1.21
  commands:
    - kubectl wait --for=condition=Ready nodes --all --timeout=60s

- name: helm-lint
  image: alpine/helm:3.5.4
  commands:
    - helm lint . -f values.yaml

- name: helm-install
  image: alpine/helm:3.5.4
  commands:
    - helm install test-release . -f values.yaml

- name: verify-deployment
  image: bitnami/kubectl:1.21
  commands:
    - kubectl get pods

trigger:
  event:
    - push
    - pull_request
  branch:
    - main

---
kind: pipeline
type: docker
name: publish


trigger:
  branch:
    - custom

steps:
  - name: publish helm chart to github pages
    image: otwld/drone-chart-releaser-github-pages
    settings:
      cr_token:
        from_secret: github_access_token
      skip_existing: true
      root_package: true
